# Generated by Django 4.0.5 on 2022-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_alter_organization_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_org',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
    ]
