# Generated by Django 4.0.5 on 2022-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_alter_bill_client_name_alter_bill_client_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fraud_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='service_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
