# Generated by Django 4.0.5 on 2022-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_bill_fraud_score_bill_service_class_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
